<?php
if(Mage::getStoreConfig('landofcoder_gdpr/configuration/cookienotice'))
{
    $baseUrl = Mage::getBaseUrl();
    $baseUrl = str_replace(["https://", "/"] , "", $baseUrl);
    $noticeHtml = Mage::getSingleton('core/layout')->createBlock('cms/block')->setBlockId('gdpr-content')->toHtml();
    $noticeHtml = $noticeHtml ? $noticeHtml : $this->__('This website (%s) uses cookies to ensure proper functionality of our shopping cart and checkout progress. By continuing to browse the site you are agreeing to the use of cookies.', $baseUrl);

    $cookieTitle = Mage::getStoreConfig('landofcoder_gdpr/configuration/cookietitle');
    $cookieTitle = $cookieTitle ? $cookieTitle : $this->__('Cookie Policy');
    $linktitle = Mage::getStoreConfig('landofcoder_gdpr/configuration/linktitle');
    $linktitle = $linktitle ? $linktitle : $this->__('Click here to learn about cookie settings.');
    $acceptlabel = Mage::getStoreConfig('landofcoder_gdpr/configuration/acceptlabel');
    $acceptlabel = $acceptlabel ? $acceptlabel : $this->__('Accept');
    ?>
<div id="cookiealert" class="cookiealert" style="display: none;">
    <div class="message">
        <span class="cookie-title"><?php echo $cookieTitle;?></span>
        <p>
            <?php echo $noticeHtml; ?>
            <a href="javascript:;" class="open-modal-policy" id="openGdprPolicyPopup" data-toggle="modal" data-target="#modalLogImpressum"><?php echo $linktitle; ?></a>
        </p>
        <p class="accept" style="width: 50%; display: inline-block;">
            <a href="javascript:acceptCookieAlert();"><?php echo $acceptlabel;?></a>
        </p>
        
    </div>
</div>

<script type="text/javascript">
function closeCookieAlert() {
    Mage.Cookies.set('cookieAlertClosedFlag', 1, new Date(new Date().getTime() + (1000 * 60 * 60 * 24 * 364)));
    document.getElementById('cookiealert').style.display = 'none';
}

function acceptCookieAlert() {
    closeCookieAlert();
    Mage.Cookies.set('cookieAlertState', 1, new Date(new Date().getTime() + (1000 * 60 * 60 * 24 * 364)));
    loadCookieScript();
}

function declineCookieAlert() {
    closeCookieAlert();
    Mage.Cookies.set('cookieAlertState', 0, new Date(new Date().getTime() + (1000 * 60 * 60 * 24 * 364)));
}

function loadCookieScript() {
<?php
$gtmContainerId = Mage::getStoreConfig('landofcoder_gdpr/configuration/gtm_container_id');
if (!empty($gtmContainerId)) {
    ?>
    var script = document.createElement('script');
    script.type = 'text/javascript';
    script.text = 'var Translator = new Translate([]);';
    document.body.appendChild(script);
    
    var gtm_tag = document.createElement('script');
    gtm_tag.type = 'text/javascript';
    gtm_tag.text = '(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\':new Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=\'https://www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);})(window,document,\'script\',\'dataLayer\',\'<?php echo $gtmContainerId; ?>\');';
    document.body.appendChild(gtm_tag);
    <?php
}
?>
}

if (!Mage.Cookies.get('cookieAlertClosedFlag')) {
    document.getElementById('cookiealert').style.display = '';
}

if (Mage.Cookies.get('cookieAlertState') == 1) {
    loadCookieScript();
}
</script>
    <?php
}
